# Generated by Django 6.0.2 on 2026-02-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelproject',
            options={'ordering': ['-created_at']},
        ),
    ]
